{
 "title": "Jenkins",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Build Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Build Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "cpu_p",
       "id": "1",
       "settings": {
        "percents": [
         "25",
         "50",
         "75",
         "95",
         "99"
        ]
       },
       "type": "percentiles"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Build Start Times",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "message:STARTED",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}