# elasticsearch.yaml
# apiVersion: elasticsearch.k8s.elastic.co/v1
# kind: Elasticsearch
# metadata:
#   name: elasticsearch
#   namespace: devops-tools
# spec:
#   version: 8.12.2
#   nodeSets:
#   - name: default
#     count: 1
#     config:
#       node.store.allow_mmap: false


apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: devops-tools
spec:
  version: 7.17.7
  nodeSets:
  - name: default
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
