apiVersion: v1
kind: Service
metadata:
  name: tomcat-service-xfusion
  namespace: devops-tools
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 32228
---
apiVersion: apps/v1                          
kind: Deployment
metadata:
  name: tomcat-deployment-xfusion
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat-container-xfusion
          image: gcr.io/kodekloud/centos-ssh-enabled:tomcat
          ports:
            - containerPort: 8080