apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-credentials
  namespace: logging
type: Opaque
data:
  ELASTICSEARCH_USER: ZWxhc3RpYw==
  ELASTICSEARCH_PASSWORD: bDY0Yjh1NjBONjhYRmdHMjNrTVZnOXF0
