apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: logstash:8.12.2 # Replace with your Logstash Docker image
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: jenkins-logs
          mountPath: /var/jenkins_home/jobs/ # Assuming Jenkins logs are stored in this directory
      volumes:
      - name: jenkins-logs
        emptyDir: {} # Using an emptyDir volume, replace with appropriate volume if needed
